all:
	gcc -std=c99 -Werror -Wpedantic -Wall -o3 ./Stack_asm/main.c -o stack_asm
	gcc -std=c99 -Werror -Wpedantic -Wall -o3 ./Stack_disasm/main.c -o stack_disasm
	gcc -std=c99 -Werror -Wpedantic -Wall -o3 ./Stack_cpu/main.c -o stack_cpu -lm
